# Generated by Django 2.2.1 on 2019-06-04 05:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follow',
            field=models.CharField(max_length=50, verbose_name='追加'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=200, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='post',
            name='touser',
            field=models.CharField(max_length=200, verbose_name='宛先'),
        ),
    ]
